function render(){if(state.mode==="duel"){renderMultiplayerLobby();return}if(state.mode==="geo")renderGeo();if(state.mode==="pov")renderPOV();if(state.mode==="arc")renderArc();if(state.mode==="visitors")renderVisitors();if(state.mode==="region")renderRegion();if(state.mode==="timeline")renderTimeline()}
function mapLabels(realm){const labs=realm==="overworld"?[[50,50,"Spawn"],[23,24,"Amplified"],[84,18,"Great Sea"],[6,48,"Far Lands"],[49,8,"Mist"],[66,58,"Wonders"]]:realm==="nether"?[[33,44,"Clown Territory"],[59,55,"Purgatory"],[81,76,"Underworld"]]:[[52,48,"End Civilization"],[76,56,"Deep End"]];return labs.map(([x,y,t])=>`<div class="region" style="left:${x}%;top:${y}%">${t}</div>`).join("")}
function mapNodes(realm){const pool=POIS.filter(p=>p.realm===realm);return pool.map(p=>`<div class="poi-node ${realm==='nether'?'nether':realm==='end'?'end':''} ${PHOTO_MAP[p.n]?'major':''}" style="left:${p.x}%;top:${p.y}%"></div>`).join('')}
function voxelMapSVG(realm){return ""}
function renderMap(){return `<div class="map-wrap"><div class="realm-tabs">${["overworld","nether","end"].map(r=>`<button class="realm-tab ${state.realm===r?'active':''}" data-realm="${r}">${r==="overworld"?'Overworld':r==="nether"?'Nether / Underworld':'The End'}</button>`).join("")}</div><div class="map ${state.realm}" id="map">${voxelMapSVG(state.realm)}${mapNodes(state.realm)}${mapLabels(state.realm)}</div><div class="map-key"><span><i class="key-dot major"></i>playable photo POI</span><span><i class="key-dot ${state.realm==='nether'?'nether':state.realm==='end'?'end':''}"></i>all mapped POIs</span></div><div class="map-note">Lore-relative map. POI pins are laid out relative to Unstable geography, not exact canonical block coordinates.</div></div>`}
function renderGeo(){const p=state.current;main.innerHTML=header("Geo Guess","Use the clues, choose the correct realm, then click where you think this POI belongs.")+`<div class="play-area">${sceneCard(p)}<div class="question"><h3>Drop your pin</h3><div class="prompt">Wrong realm = heavy penalty. You can move the pin until you lock the guess.</div>${renderMap()}<div style="margin-top:10px"><button class="btn primary" id="lockGuess" disabled>Lock guess</button></div><div id="feedback" class="feedback"></div></div></div>`;
  document.querySelectorAll('.realm-tab').forEach(b=>b.onclick=()=>{if(state.answered)return;state.realm=b.dataset.realm;renderGeo()});
  const map=$("#map"), lock=$("#lockGuess");map.onclick=e=>{if(state.answered)return;const r=map.getBoundingClientRect();state.guess={x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100,realm:state.realm};const old=map.querySelector('.pin.guess');if(old)old.remove();const pin=document.createElement('div');pin.className='pin guess';pin.style.left=state.guess.x+'%';pin.style.top=state.guess.y+'%';map.appendChild(pin);lock.disabled=false};
  lock.onclick=()=>{if(!state.guess||state.answered)return;state.answered=true;let pts=0,dist=999;if(state.guess.realm===p.realm){dist=Math.hypot(state.guess.x-p.x,state.guess.y-p.y);pts=Math.max(0,Math.round(5000*(1-dist/90)))}else pts=250;state.score+=pts;state.streak=pts>=3500?state.streak+1:0;setBest();if(state.realm!==p.realm){state.realm=p.realm;renderGeo();setTimeout(()=>revealGeo(p,pts,dist),0)}else revealGeo(p,pts,dist)};
}
function revealGeo(p,pts,dist){state.answered=true;const map=$("#map");if(!map)return;const truth=document.createElement('div');truth.className='pin truth';truth.style.left=p.x+'%';truth.style.top=p.y+'%';map.appendChild(truth);if(state.guess&&state.guess.realm===p.realm){const dx=(p.x-state.guess.x)/100*map.clientWidth,dy=(p.y-state.guess.y)/100*map.clientHeight;const len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;const line=document.createElement('div');line.className='line';line.style.left=state.guess.x+'%';line.style.top=state.guess.y+'%';line.style.width=len+'px';line.style.transform=`rotate(${ang}deg)`;map.appendChild(line)}
  const lock=$("#lockGuess");if(lock)lock.disabled=true;finishFeedback(pts>=3500,`<b>${p.n}</b> • ${p.region}<br>You scored <b>${pts.toLocaleString()}</b> / 5,000${isFinite(dist)?` • distance ${dist.toFixed(1)} lore-map units`:''}.`)
}
function fourChoices(answer,source=POVS){const opts=shuffle([answer,...sample(source.filter(x=>x!==answer),3)]);return opts.map(o=>`<button class="choice" data-value="${o}">${o}</button>`).join("")}
function renderPOV(){const r=state.current,answer=r.pov;main.innerHTML=header("Guess the POV","Identify the POV from in-game gameplay shots only. Thumbnail-style images are removed from POV mode.")+`<div class="play-area">${povSceneCard(r)}<div class="question"><h3>Whose POV is this?</h3><div class="prompt">Use the environment, build style, and arc context. POV mode excludes thumbnail art and uses full in-game shots only.</div><div class="choices">${fourChoices(answer)}</div><div id="feedback" class="feedback"></div></div></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(state.answered)return;state.answered=true;const ok=b.dataset.value===answer;document.querySelectorAll('.choice').forEach(x=>{if(x.dataset.value===answer)x.classList.add('correct');else if(x===b)x.classList.add('wrong')});answerPoints(ok);finishFeedback(ok,ok?`Correct — this is <b>${answer}</b>'s POV capture.`:`This capture is from <b>${answer}</b>'s POV.`)})}
function renderArc(){const p=state.current;const pool=uniq(POIS.map(x=>x.arc));const opts=shuffle([p.arc,...sample(pool.filter(x=>x!==p.arc),3)]);main.innerHTML=header("Guess the Arc","Match the location to the storyline arc that best fits it.")+`<div class="play-area">${sceneCard(p)}<div class="question"><h3>${p.n}</h3><div class="prompt">Which arc is the best match?</div><div class="choices">${opts.map(o=>`<button class="choice" data-value="${o}">${o}</button>`).join('')}</div><div id="feedback" class="feedback"></div></div></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(state.answered)return;state.answered=true;const ok=b.dataset.value===p.arc;document.querySelectorAll('.choice').forEach(x=>{if(x.dataset.value===p.arc)x.classList.add('correct');else if(x===b)x.classList.add('wrong')});answerPoints(ok);finishFeedback(ok,`<b>${p.n}</b> is filed under <b>${p.arc}</b> in this prototype.`)})}
function renderVisitors(){const p=state.current;main.innerHTML=header("Who Visited?","Select every main POV confirmed in this prototype dataset, then submit.")+`<div class="play-area">${sceneCard(p)}<div class="question"><h3>${p.n}</h3><div class="prompt">Multiple answers may be correct.</div><div class="multi">${POVS.map(x=>`<button class="toggle" data-value="${x}">${x}</button>`).join('')}</div><div style="margin-top:10px"><button class="btn primary" id="submitVisitors">Submit</button></div><div id="feedback" class="feedback"></div></div></div>`;const chosen=new Set();document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>{if(state.answered)return;const v=b.dataset.value;chosen.has(v)?chosen.delete(v):chosen.add(v);b.classList.toggle('on')});$("#submitVisitors").onclick=()=>{if(state.answered)return;state.answered=true;const truth=new Set(p.v);const ok=POVS.every(x=>chosen.has(x)===truth.has(x));document.querySelectorAll('.toggle').forEach(b=>{if(truth.has(b.dataset.value))b.classList.add('correct');else if(chosen.has(b.dataset.value))b.classList.add('wrong')});answerPoints(ok,1400);finishFeedback(ok,`Confirmed visitors in this build: <b>${p.v.join(', ')}</b>.`)}}
function renderRegion(){const p=state.current;const regions=uniq(POIS.map(x=>x.region));const opts=shuffle([p.region,...sample(regions.filter(x=>x!==p.region),3)]);main.innerHTML=header("Place It","Identify the parent region or major map cluster.")+`<div class="play-area">${sceneCard(p)}<div class="question"><h3>${p.n}</h3><div class="prompt">Which region contains this POI?</div><div class="choices">${opts.map(o=>`<button class="choice" data-value="${o}">${o}</button>`).join('')}</div><div id="feedback" class="feedback"></div></div></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(state.answered)return;state.answered=true;const ok=b.dataset.value===p.region;document.querySelectorAll('.choice').forEach(x=>{if(x.dataset.value===p.region)x.classList.add('correct');else if(x===b)x.classList.add('wrong')});answerPoints(ok);finishFeedback(ok,`<b>${p.n}</b> is placed in <b>${p.region}</b>.`)})}
function renderTimeline(){
  const a=state.current;
  const b=popNextPoi(x=>x.n!==a.n&&Math.abs(x.debut-a.debut)>4) || popNextPoi(x=>x.n!==a.n);
  if(!b){finishFeedback(false,'Not enough unique photo POIs left for another timeline duel.');return}
  state.current={a,b};
  main.innerHTML=header("Timeline Duel","Both locations are shown. Pick which one appeared earlier in the story.")+`<div class="question"><div class="duel-grid">${duelImageCard(a)}${duelImageCard(b)}</div><div class="duel-choice-grid"><button class="choice" data-value="a">${a.n}</button><button class="choice" data-value="b">${b.n}</button></div><div id="feedback" class="feedback"></div></div>`;
  document.querySelectorAll('.choice').forEach(btn=>btn.onclick=()=>{if(state.answered)return;state.answered=true;const correct=a.debut<b.debut?'a':'b',ok=btn.dataset.value===correct;document.querySelectorAll('.choice').forEach(x=>{if(x.dataset.value===correct)x.classList.add('correct');else if(x===btn)x.classList.add('wrong')});answerPoints(ok);const first=correct==='a'?a:b,second=correct==='a'?b:a;finishFeedback(ok,`<b>${first.n}</b> appeared earlier than <b>${second.n}</b> in this game chronology.`)})}
