const duel={peer:null,conn:null,isHost:false,room:"",name:"Player",opponent:"Opponent",rounds:[],index:0,scores:{host:0,guest:0},answers:{},timer:null,roundStarted:0,connected:false};
function duelCleanup(){if(duel.timer)clearTimeout(duel.timer);duel.timer=null;try{duel.conn?.close()}catch(e){}try{duel.peer?.destroy()}catch(e){}duel.peer=null;duel.conn=null;duel.connected=false;duel.rounds=[];duel.answers={};duel.index=0;duel.scores={host:0,guest:0}}
function duelCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function duelSetStatus(msg){const el=document.querySelector('#duelStatus');if(el)el.innerHTML=msg}
function renderMultiplayerLobby(){duelCleanup();main.innerHTML=header("1v1 Multiplayer","Create a room or join a friend's room. Both players get the same rounds; correct and faster answers score more.")+`<div class="duel-lobby"><div class="duel-box"><h3>Create room</h3><p>Host a direct browser-to-browser match. Share the room code with one friend.</p><input id="duelNameHost" class="duel-input" maxlength="20" placeholder="Your name" value="Player 1"><button class="btn primary" id="hostDuel">Create room</button></div><div class="duel-box"><h3>Join room</h3><p>Enter the six-character code from the host.</p><input id="duelNameJoin" class="duel-input" maxlength="20" placeholder="Your name" value="Player 2"><input id="duelRoomJoin" class="duel-input" maxlength="6" placeholder="ROOM CODE" style="text-transform:uppercase"><button class="btn primary" id="joinDuel">Join room</button></div></div><div id="duelStatus" class="duel-status" style="margin-top:14px">Peer-to-peer multiplayer uses WebRTC. Keep this tab open while playing.</div>`;
  document.querySelector('#hostDuel').onclick=duelHost;
  document.querySelector('#joinDuel').onclick=duelJoin;
}
function duelPeerReady(peer,onOpen){peer.on('error',e=>duelSetStatus(`<b>Connection error:</b> ${e.type||e.message}`));peer.on('disconnected',()=>duelSetStatus('Connection to signaling service lost. Refresh or create a new room.'));peer.on('open',onOpen)}
function duelHost(){if(typeof Peer==='undefined'){duelSetStatus('Multiplayer library failed to load. Check your internet connection and refresh.');return}duelCleanup();duel.isHost=true;duel.name=(document.querySelector('#duelNameHost')?.value||'Player 1').trim().slice(0,20)||'Player 1';duel.room=duelCode();const id='unstable-'+duel.room.toLowerCase();duel.peer=new Peer(id);duelSetStatus('Creating room…');duelPeerReady(duel.peer,()=>{main.innerHTML=header("1v1 Multiplayer","Room created. Share the code below.")+`<div class="duel-box" style="max-width:650px;margin:auto;text-align:center"><div class="sub">ROOM CODE</div><div class="room-code">${duel.room}</div><div id="duelStatus" class="duel-status">Waiting for opponent…</div><div style="margin-top:12px"><button class="btn ghost" onclick="navigator.clipboard?.writeText('${duel.room}')">Copy code</button></div></div>`});duel.peer.on('connection',conn=>{if(duel.conn){conn.close();return}duel.conn=conn;duelBindConnection(conn)})}
function duelJoin(){if(typeof Peer==='undefined'){duelSetStatus('Multiplayer library failed to load. Check your internet connection and refresh.');return}const room=(document.querySelector('#duelRoomJoin')?.value||'').trim().toUpperCase();if(room.length!==6){duelSetStatus('Enter the six-character room code.');return}duelCleanup();duel.isHost=false;duel.room=room;duel.name=(document.querySelector('#duelNameJoin')?.value||'Player 2').trim().slice(0,20)||'Player 2';duel.peer=new Peer();duelSetStatus('Connecting…');duelPeerReady(duel.peer,()=>{duel.conn=duel.peer.connect('unstable-'+room.toLowerCase(),{reliable:true});duelBindConnection(duel.conn)})}
