function duelBindConnection(conn){conn.on('open',()=>{duel.connected=true;if(duel.isHost){duelSetStatus('<span class="online-dot"></span>Opponent connected. Waiting for their name…')}else{conn.send({t:'hello',name:duel.name});duelSetStatus('<span class="online-dot"></span>Connected. Waiting for the host to start…')}});conn.on('data',duelMessage);conn.on('close',()=>{duel.connected=false;duelSetStatus('Opponent disconnected.')});conn.on('error',e=>duelSetStatus(`Connection error: ${e.message||e}`))}
function duelMessage(msg){if(!msg||!msg.t)return;if(msg.t==='hello'&&duel.isHost){duel.opponent=(msg.name||'Opponent').slice(0,20);duel.conn.send({t:'welcome',name:duel.name});renderDuelHostReady();return}if(msg.t==='welcome'&&!duel.isHost){duel.opponent=(msg.name||'Host').slice(0,20);renderDuelGuestWaiting();return}if(msg.t==='start'&&!duel.isHost){duel.rounds=msg.rounds;duel.scores=msg.scores||{host:0,guest:0};duel.index=0;renderDuelRound();return}if(msg.t==='answer'&&duel.isHost){duel.answers.guest=msg;duelMaybeFinishRound();return}if(msg.t==='result'&&!duel.isHost){duel.scores=msg.scores;renderDuelRoundResult(msg);return}if(msg.t==='next'&&!duel.isHost){duel.index=msg.index;renderDuelRound();return}if(msg.t==='gameover'&&!duel.isHost){duel.scores=msg.scores;renderDuelGameOver();return}}
function renderDuelHostReady(){main.innerHTML=header("1v1 Multiplayer","Opponent connected. Start when you're ready.")+`<div class="duel-box" style="max-width:650px;margin:auto"><div class="duel-scorebar"><div class="duel-player me"><b>${duel.name}</b><span>Host</span></div><div class="duel-player"><b>${duel.opponent}</b><span>Opponent</span></div></div><div class="duel-status"><span class="online-dot"></span>Room ${duel.room} is ready.</div><button class="btn primary" id="startDuel" style="margin-top:12px;width:100%">Start ${Math.min(+document.querySelector('#roundCount')?.value||10,10)}-round duel</button></div>`;document.querySelector('#startDuel').onclick=duelStart}
function renderDuelGuestWaiting(){main.innerHTML=header("1v1 Multiplayer","Connected to the host.")+`<div class="duel-box" style="max-width:650px;margin:auto;text-align:center"><div class="duel-scorebar"><div class="duel-player"><b>${duel.opponent}</b><span>Host</span></div><div class="duel-player me"><b>${duel.name}</b><span>You</span></div></div><div class="duel-status"><span class="online-dot"></span>Waiting for ${duel.opponent} to start the match…</div></div>`}
function duelBuildRounds(){const total=Math.min(+document.querySelector('#roundCount')?.value||10,10,ACTIVE_POIS.length);const selected=shuffle(ACTIVE_POIS).slice(0,total);return selected.map(p=>{const distract=shuffle(ACTIVE_POIS.filter(x=>x.n!==p.n)).slice(0,3).map(x=>x.n);return {answer:p.n,choices:shuffle([p.n,...distract])}})}
function duelStart(){duel.rounds=duelBuildRounds();duel.index=0;duel.scores={host:0,guest:0};duel.answers={};duel.conn.send({t:'start',rounds:duel.rounds,scores:duel.scores});renderDuelRound()}
function duelCurrentPoi(){const r=duel.rounds[duel.index];return ACTIVE_POIS.find(p=>p.n===r?.answer)}
function renderDuelRound(){state.answered=false;if(duel.index>=duel.rounds.length){if(duel.isHost){duel.conn.send({t:'gameover',scores:duel.scores})}renderDuelGameOver();return}duel.answers={};const r=duel.rounds[duel.index],p=duelCurrentPoi();duel.roundStarted=performance.now();main.innerHTML=header("1v1 Multiplayer",`Round ${duel.index+1} of ${duel.rounds.length}`)+`<div class="duel-scorebar"><div class="duel-player ${duel.isHost?'me':''}"><b>${duel.isHost?duel.name:duel.opponent}</b><span>${duel.scores.host.toLocaleString()} pts</span></div><div class="duel-player ${!duel.isHost?'me':''}"><b>${duel.isHost?duel.opponent:duel.name}</b><span>${duel.scores.guest.toLocaleString()} pts</span></div></div><div class="play-area">${sceneCard(p)}<div class="question"><h3>Which location is this?</h3><div class="prompt">Both players see the same round. Correct answers earn 1,000 points plus a speed bonus.</div><div class="duel-timer"><i id="duelTimerBar"></i></div><div class="duel-choice-grid">${r.choices.map(c=>`<button class="choice duel-answer" data-value="${c}">${c}</button>`).join('')}</div><div id="feedback" class="feedback"></div></div></div>`;document.querySelectorAll('.duel-answer').forEach(b=>b.onclick=()=>duelSubmitAnswer(b.dataset.value));duelAnimateTimer();if(duel.isHost){duel.timer=setTimeout(()=>duelForceFinish(),16000)}}
function duelAnimateTimer(){const bar=document.querySelector('#duelTimerBar');if(!bar)return;bar.animate([{transform:'scaleX(1)'},{transform:'scaleX(0)'}],{duration:15000,fill:'forwards',easing:'linear'})}
function duelPoints(choice,elapsed){const correct=choice===duel.rounds[duel.index].answer;if(!correct)return 0;return 1000+Math.max(0,Math.round(1000*(1-Math.min(elapsed,15000)/15000)))}
function duelSubmitAnswer(choice){if(state.answered)return;state.answered=true;const elapsed=performance.now()-duel.roundStarted,points=duelPoints(choice,elapsed),payload={t:'answer',index:duel.index,choice,elapsed,points};document.querySelectorAll('.duel-answer').forEach(b=>{b.disabled=true;if(b.dataset.value===duel.rounds[duel.index].answer)b.classList.add('correct');else if(b.dataset.value===choice)b.classList.add('wrong')});const f=document.querySelector('#feedback');if(f){f.className='feedback show '+(points?'good':'bad');f.innerHTML=points?`Locked in — <b>${points.toLocaleString()}</b> points. Waiting for opponent…`:'Locked in. Waiting for opponent…'}if(duel.isHost){duel.answers.host=payload;duelMaybeFinishRound()}else{duel.conn.send(payload)}}
function duelForceFinish(){if(!duel.isHost)return;if(!duel.answers.host)duel.answers.host={choice:null,points:0,elapsed:15000};if(!duel.answers.guest)duel.answers.guest={choice:null,points:0,elapsed:15000};duelFinishRound()}
function duelMaybeFinishRound(){if(!duel.isHost)return;if(duel.answers.host&&duel.answers.guest){if(duel.timer)clearTimeout(duel.timer);duelFinishRound()}}
function duelFinishRound(){if(!duel.isHost)return;duel.scores.host+=duel.answers.host?.points||0;duel.scores.guest+=duel.answers.guest?.points||0;const result={t:'result',index:duel.index,correct:duel.rounds[duel.index].answer,scores:duel.scores,host:duel.answers.host||{},guest:duel.answers.guest||{}};duel.conn.send(result);renderDuelRoundResult(result)}
function renderDuelRoundResult(result){const mine=duel.isHost?result.host:result.guest,other=duel.isHost?result.guest:result.host;main.innerHTML=header("1v1 Multiplayer",`Round ${duel.index+1} result`)+`<div class="duel-box" style="max-width:720px;margin:auto"><h3>Correct location: ${result.correct}</h3><div class="duel-scorebar"><div class="duel-player ${duel.isHost?'me':''}"><b>${duel.isHost?duel.name:duel.opponent}</b><span>${result.scores.host.toLocaleString()} pts</span></div><div class="duel-player ${!duel.isHost?'me':''}"><b>${duel.isHost?duel.opponent:duel.name}</b><span>${result.scores.guest.toLocaleString()} pts</span></div></div><div class="duel-result">You earned <b>${(mine?.points||0).toLocaleString()}</b> this round. Opponent earned <b>${(other?.points||0).toLocaleString()}</b>.</div><div class="duel-waiting">${duel.isHost?'Next round starting…':'Waiting for host…'}</div></div>`;if(duel.isHost){setTimeout(()=>{duel.index++;if(duel.index>=duel.rounds.length){duel.conn.send({t:'gameover',scores:duel.scores});renderDuelGameOver()}else{duel.conn.send({t:'next',index:duel.index});renderDuelRound()}},2200)}}
function renderDuelGameOver(){const myScore=duel.isHost?duel.scores.host:duel.scores.guest,oppScore=duel.isHost?duel.scores.guest:duel.scores.host,win=myScore===oppScore?'Tie game':myScore>oppScore?'You win!':'Opponent wins';main.innerHTML=header("1v1 Multiplayer","Match complete")+`<div class="duel-box" style="max-width:650px;margin:auto;text-align:center"><div class="sub">FINAL RESULT</div><h2 style="font-size:34px;margin:8px 0">${win}</h2><div class="duel-scorebar"><div class="duel-player me"><b>${duel.name}</b><span>${myScore.toLocaleString()} pts</span></div><div class="duel-player"><b>${duel.opponent}</b><span>${oppScore.toLocaleString()} pts</span></div></div><button class="btn primary" onclick="renderMultiplayerLobby()">Play another 1v1</button></div>`}

$("#newGame").onclick=newGame;$("#skip").onclick=()=>{state.streak=0;updateStats();nextRound()};
initModes();updateStats();
main.innerHTML=`<div class="start"><div class="start-shell"><span class="start-kicker">PHOTO EDITION</span><h2>UNSTABLE LOCATOR</h2><p>GeoGuessr-style Unstable rounds with photo POIs, in-game POV rounds, no repeated POIs, Timeline Duels, and live 1v1 multiplayer.</p><div class="start-gallery"><img ${imageAttrs(PHOTO_MAP['Mafia City'].shots[0])} onerror="imgOnError(this)" alt="Unstable location preview"><img ${imageAttrs(PHOTO_MAP['Great Sea'].shots[0])} onerror="imgOnError(this)" alt="Unstable location preview"><img ${imageAttrs(PHOTO_MAP['Paragon'].shots[0])} onerror="imgOnError(this)" alt="Unstable location preview"><img ${imageAttrs(PHOTO_MAP['Frosted Palace'].shots[0])} onerror="imgOnError(this)" alt="Unstable location preview"></div><div class="photo-note">${ACTIVE_POIS.length} curated visual POIs are active • ${POIS.length} lore POIs are mapped • multiplayer is browser-to-browser through WebRTC.</div><button class="btn primary" onclick="newGame()">Start photo run</button></div></div>`;
